# Generated by Django 4.2 on 2023-05-22 18:51

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='imagem',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='titulo'),
        ),
    ]
