# Generated by Django 4.2 on 2023-05-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_imagem_noticia_image_alter_categoria_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
