# Generated by Django 4.2 on 2023-05-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campanha', models.CharField(max_length=200)),
                ('destaque', models.ImageField(blank=True, upload_to='destaque/%Y/%m/%d')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='link de acesso')),
                ('is_available', models.BooleanField(default=True, verbose_name='Esse destaque esta ativo?')),
            ],
            options={
                'verbose_name': 'Destaque',
                'verbose_name_plural': 'Imagens de destaque',
            },
        ),
    ]
